### ISSUE TITLE
PermissionError: [Errno 13] error while attempting to bind on address ('::', 80, 0, 0)

### ISSUE THREAD

**Issue by chvieira2** [All-About-Berlin/burgeramt-appointments#24]
Hey. First of all, thanks for putting the effort!

While running "appointments" locally (I've downloaded the code and am running it in VS code instead of Bash), I'm getting a permission error. I'm running the code from my work computer, so I'm wondering if this is a known error with a easy fix or if this might be caused by the firewall protections in my corporate computer.

PS.: I've removed private info like my email and username from the error message

What is URL of the service you want to watch?
This is service.berlin.de page for the service you want an appointment for. For example, "https://service.berlin.de/dienstleistung/120686/"
> https://service.berlin.de/dienstleistung/120686/
What is your email address?
It will be included in the requests this script makes. It's required by the Berlin.de appointments team.
> myemail@myemail.com
[2024-04-04 17:31:06] INFO: Getting appointment URL for https://service.berlin.de/dienstleistung/120686/
[2024-04-04 17:31:06] INFO: URL found: https://service.berlin.de/terminvereinbarung/termin/all/120686/
Traceback (most recent call last):
  File "c:\Users\XXX\Projects\burgeramt-appointments-main\bin\appointments", line 67, in <module>
    asyncio.run(watch_for_appointments(service_page_url, email, args.id, args.port, args.quiet))
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete        
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\appointments\appointments.py", line 165, in watch_for_appointments
    async with websockets.serve(on_connect, port=server_port):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 1068, in __aenter__
    return await self
           ^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\websockets\legacy\server.py", line 1086, in __await_impl__
    server = await self._create_server()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1525, in create_server
    raise OSError(err.errno, 'error while attempting '
PermissionError: [Errno 13] error while attempting to bind on address ('::', 80, 0, 0): an attempt was made to access a socket in a way forbidden by its access permissions

**Comment by nicbou** [comment]
I Googled the error message and it says to try a different port.

**Comment by thiagoribeir015** [comment]
```
appointments --port 8081
```

managed to get it running on a different port, but now i'm getting only 403s :/ 

```
[2024-04-05 14:42:40] INFO: Server is running on port 8081. Looking for appointments every 180 seconds.
[2024-04-05 14:42:40] WARNING: Got 403 error. Checking in 180 seconds
[2024-04-05 14:45:40] WARNING: Got 403 error. Checking in 180 seconds
```

**Comment by nicbou** [comment]
That's unfortunately not a problem on your side. The city is blocking your requests.

**Comment by bellonet** [comment]
Hi @nicbou, I also get a 403 warning. Do you know why some users are blocked? 
I didn't change the script, and only call `appointments` with the port argument.
Thank you for the tool!

**Comment by coyotebush** [comment]
Regarding the original issue, it would be nice if the default configuration used a port number of 1024 or higher, or simply didn't bind to a port at all. Otherwise Mac/Linux users (at least) will experience friction and either learn to use `--port` or (worse) run the entire script with `sudo`.
